export const VALIDATIONMSG = {
  firstName: 'Please enter patient\'s first and last name.',
  phone: 'Please enter a valid 10-digit phone number.',
  dob: 'Date of Birth is required.',
  dobValid: 'Please enter valid date.',
  email: 'Email is required.',
  emailValid: 'Please enter valid email.',
  street: 'Street is required.',
  city: 'City is required.',
  state: 'State is required.',
  zipcodeMsg: 'Zip Code is required.',
  zipcodeValid: 'Please enter valid zipcode.',
  doctorName: 'Please enter your doctor\'s first and last name.',
  doctorPhone: 'Please enter a valid 10-digit phone number.',
  drugName: 'Please enter a drug name and strength (e.g., Lipitor 40mg)',
  drugQuantity: 'Please enter a drug quantity.',
  drugQuantityValid: 'Please enter a valid drug quantity(e.g., 12)',
  pcanewHeader: 'Request New Home Delivery Prescription',
  patientInfo: 'Patient Information',
  errorInfo: 'Error',
  shipAddress: 'Shipping Address',
  ImportWarn1: 'Additional processing time is required for this request',
  ImportWarn2: 'Once processed, orders are shipped by Standard (Free) Shipping method. Arrival in 5-10 business days.',
  newPrescription: 'New Prescription',
  doctorFirstNamelabel: 'Doctor\'s first and last name',
  doctorPhonelabel: 'Doctor’s phone number',
  drugNameLabel: 'Drug name and strength',
  drugQuantityLabel: 'Drug quantity',
  generalWarnMsg: 'Generic equivalent not accepted.',
  addAnotherPrescription: 'Add another prescription',
  limitOrderWarn: 'You have reached the limit of new prescriptions per order.',
  submitReq: 'Submit request',
  cancel: 'Cancel',
  cancelWarningNew: 'Are you sure you want to cancel this request for a new prescription? Your information won’t be saved.',
  cancelWarningTransfer: 'Are you sure you want to cancel this request to transfer a prescription? Your information won’t be saved.',
  warnMsg1: 'No, go back',
  warnMsg2: 'Yes, cancel request',
  removeWarning: 'Are you sure you want to delete this prescription? Your information won\'t be saved.',
  removeWarningMsg1: 'No',
  removeWarningMsg2: 'Yes, delete',
  firstNameLabel: 'First and Last name',
  phoneNumberlabel: 'Phone number',
  doblabel: 'Date of Birth',
  emaillabel: 'Email Address',
  citylabel: 'City',
  statelabel: 'State',
  zipcodelabel: 'Zip Code',
  pharmacyName: 'Pharmacy Name',
  pharmacyNameMsg: 'Please enter pharmacy name',
  pharmacyPhoneNumber: 'Pharmacy phone number',
  pharmacyPhoneNumberMsg: 'Please enter a valid 10-digit pharmacy phone number',
  prescriptionName: 'Prescription Name',
  prescriptionNameName: 'Please enter a prescription name',
  prescriptionNumber: 'Prescription number (Optional)',
  previousPharmacyInformation: 'Previous Pharmacy Information',
  pcaTransferHeader: 'Home Delivery Prescription Transfer Request'
};
